### ISSUE TITLE
Extend student frequency list with readonly field

### ISSUE THREAD

**Issue by Kipoderax** [wiotrek/ElectronicDiary4School#104]
readonly = 1: display readonly frequency list
readonly = 0: teacher can edit frequency list

**Comment by wiotrek** [comment]
Json object output from backend, will look like this?

{
    readonly: number,
    StudentActivity: [
      {
        student: Student;
        isActive: boolean;
      }
    ]
  }

**Comment by Kipoderax** [comment]
Better boolean type for readonly field

**Comment by Kipoderax** [comment]
And please add date as string additionally. 
If teacher enter to frequency list 2 days after lesson then you can put this date to calendar as frequency for this date
Thank you very much.
